### PR TITLE
The termux requirements / dependencies file

### PR DESCRIPTION
**Pull request by roberts01**

### CODE REVIEW

**Comment by roberts01** [comment]
This is pretty close to the termux/helpers/termux_dependencies.py  file

**Comment by YuvrajRaghuvanshiS** [comment]
Base was master and changing it to termux created this mess.

**Comment by roberts01** [comment]
oh my goodness

**Comment by YuvrajRaghuvanshiS** [comment]
yes 🤦🏻‍♂️

**Pull request closed without merging**
